# KNN

In [62]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn 

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
from sklearn.datasets import load_iris

In [63]:
x,y=load_iris(return_X_y=True)

In [64]:
pd.DataFrame(x)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [65]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [66]:
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

In [67]:
y_pred

array([2, 1, 2, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 1, 0, 1, 2, 2, 1, 1, 2, 2,
       1, 0, 2, 1, 0, 1, 1, 0])

In [68]:
y_test

array([2, 1, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 1, 0, 1, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 1, 0, 1, 1, 0])

In [69]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 7,  0,  0],
       [ 0, 12,  2],
       [ 0,  0,  9]])

In [70]:
ac=accuracy_score(y_test,y_pred)
ac

0.9333333333333333

In [71]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      0.86      0.92        14
           2       0.82      1.00      0.90         9

    accuracy                           0.93        30
   macro avg       0.94      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30

